# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abfc2f0fdbb2fa3cb0beae18f75eaddb5424d844f0a90c8e05e3e2c77f14021fda6d535a7bfa8b7445f95ed75f7a06316e6e5e73e8e323e2f4cb369d5b181bcd

test:
  secret_key_base: b3734c114baa2d9041a956b8f68c614dbab8f16e9c0338ad850b611cdb7c78d3c254ae54c5df3c93bbff26f09e49e33d369be9575907162a0b15106e1d97e5ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
